# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(default='', upload_to='user_images')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=30)),
                ('Description', models.CharField(default='', max_length=50)),
                ('Price', models.CharField(default='', max_length=30)),
                ('Old_Price', models.CharField(default='', max_length=30)),
                ('Quantity', models.CharField(default='', max_length=30)),
                ('Catogory', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='photos',
            name='Product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Product'),
        ),
    ]
