# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20190321_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SupplierID',
            field=models.CharField(default='', max_length=30),
        ),
    ]
