# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-27 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190327_1020'),
        ('supplier', '0004_auto_20190325_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='supplier.Product')),
                ('SID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='supplier.Suppliers')),
                ('UID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
        ),
    ]
