# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-27 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Quantity',
            field=models.CharField(default='', max_length=30),
        ),
    ]
